import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import Footer from "./components/footer.js";

export default function Home() {
    return (
        <div>
            <Head>
                <title>[Redacted]</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.mainHome}>
                <div className={styles.projectContainer}>
                    <a href="/projects/personas" className={styles.projLink}>
                        <div className={styles.rect}>
                            <h2 id={styles.rectTitle}>Personas &rarr;</h2>
                            <p id={styles.rectText}>
                                An Excercise in UX Research
                            </p>
                        </div>
                    </a>
                    <a href="/projects/responsive" className={styles.projLink}>
                        <div className={styles.rect}>
                            <h2 id={styles.rectTitle}>
                                Responsive Redesign &rarr;
                            </h2>
                            <p id={styles.rectText}>
                                An Exercise in Accessibility and Plain HTML/CSS
                            </p>
                        </div>
                    </a>
                    <a href="/projects/iterative" className={styles.projLink}>
                        <div className={styles.rect}>
                            <h2 id={styles.rectTitle}>
                                Iterative Design &rarr;
                            </h2>
                            <p id={styles.rectText}>
                                An Exercise in Iterative Product Design
                            </p>
                        </div>
                    </a>
                    <a href="/projects/filter" className={styles.projLink}>
                        <div className={styles.rect}>
                            <h2 id={styles.rectTitle}>
                                Image Filtering &rarr;
                            </h2>
                            <p id={styles.rectText}>
                                An Exercise in Visualization and Next.js
                            </p>
                        </div>
                    </a>
                </div>
                <div className={styles.introContainer}>
                    <div className={styles.intro}>
                        <h1 id={styles.title}>
                            Hi, I'm <Link href="/about">[Redacted]</Link>!
                        </h1>
                        <p id={styles.description}>
                            I'm a frontend developer and an avid fan of visual
                            design.
                        </p>
                        <ul id={styles.bullets}>
                            <li>
                                <a
                                    href="https://www.google.com/"
                                    target="_blank"
                                >
                                    <Image
                                        src="/images/linkedin.svg"
                                        width={25}
                                        height={23}
                                        alt="Linkedin icon"
                                        style={{ paddingRight: "0.2em" }}
                                    />
                                    Linkedin
                                </a>
                            </li>
                            <li>
                                <a
                                    href="https://www.google.com/"
                                    target="_blank"
                                >
                                    <Image
                                        src="/images/github.svg"
                                        width={25}
                                        height={23}
                                        alt="Github icon"
                                        style={{ paddingRight: "0.2em" }}
                                    />
                                    Github
                                </a>
                            </li>
                            <li>
                                <a
                                    href="https://www.google.com/"
                                    target="_blank"
                                >
                                    <Image
                                        src="/images/file-earmark-text-fill.svg"
                                        width={25}
                                        height={23}
                                        alt="File icon"
                                        style={{ paddingRight: "0.2em" }}
                                    />
                                    Resume
                                </a>
                            </li>
                            <li>
                                <a
                                    href="https://www.google.com/"
                                    target="_blank"
                                >
                                    <Image
                                        src="/images/envelope-paper-heart-fill.svg"
                                        width={25}
                                        height={23}
                                        alt="Envelope icon"
                                        style={{ paddingRight: "0.2em" }}
                                    />
                                    Contact
                                </a>
                            </li>
                        </ul>
                    </div>
                    <div>
                        <Image
                            src="/images/me.png"
                            height={400}
                            width={340}
                            alt="Photo of me, redacted"
                        />
                    </div>
                </div>
            </main>
            <Footer />
        </div>
    );
}
